# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/kind-rb-0.1.0-x86_64/all/kind-rb-0.1.0-x86_64.rbi
#
# kind-rb-0.1.0-x86_64-darwin

module KindRb
  def self.executable; end
end
