# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `kind-rb` gem.
# Please instead update this file by running `bin/tapioca gem kind-rb`.

module KindRb
  class << self
    def executable; end
  end
end
